### ISSUE TITLE
Final form of manage.py in flask project w/docker, postgres ++ command does not seem to work.

### ISSUE THREAD

**Issue by joe-riley** [TheDigitalCatOnline/thedigitalcatonline.github.com#23]
I am able to ./manage.py scenario up users and get all of the expected output
...
docker-compose -p scenario_users -f docker/scenario_users.yml exec db psql -U postgres -d application

That command only connects to the 5432 db that is running and not the one created for the scenario for me.

How does calling scenario_users.yml (that is copied from scenario.yml with the port 5432) allow you to connect to another port like 32087 when the file is copied before the port is known with the  cmdline = docker_compose_cmdline('port db 5432') line?

**Comment by lgiordani** [comment]
Hi! So, the intended behaviour is that the `scenario.yml` (and thus `scenario_users.yml`) doesn't specify the port

``` yaml
    ports:
      - "5432"
```

So that is assigned randomly. The lines

``` python
    cmdline = docker_compose_cmdline("port db 5432")
    out = subprocess.check_output(cmdline)
    port = out.decode("utf-8").replace("\n", "").split(":")[1]
    os.environ["POSTGRES_PORT"] = port
```

should get the random port and put it in the `POSTGRES_PORT` environment variable used by `application/config.py`

``` python
class Config(object):
    """Base configuration"""

    user = os.environ["POSTGRES_USER"]
    password = os.environ["POSTGRES_PASSWORD"]
    hostname = os.environ["POSTGRES_HOSTNAME"]
    port = os.environ["POSTGRES_PORT"]
    database = os.environ["APPLICATION_DB"]
```

I double checked this in my local version and it works. If this doesn't work for you I suggest you print out the values of the steps above and see what you find. Feel free to send  a report of your findings, it might be a nasty (or stupid) bug. Thanks

**Comment by lgiordani** [comment]
@joe-riley Did you manage to make this work?

**Comment by joe-riley** [comment]
No, but I have since moved on from the team that needed that. It is safe to close out this issue so I will take care of that.
